---
# tasks file for Debian
- name: Add Jenkins package gpgkey
  apt_key:
       url: "{{ dpackage.key }}"
       state: present

- name: Add apt repository
  apt_repository:
        filename: "jenkins"
        state: present
        repo: "{{ dpackage.repo.url }}"

- name: Install Java and Jenkins
  package:
        name: "{{ item.value }}"
        state: "{{ jenkins_package_state }}"
  loop: "{{ lookup('dict', dsoftware) }}"
