---
# tasks file for OS-family RedHat

- name: Add jenkin package  gpgkey
  rpm_key:
      key: "{{ RedHat_package.key }}"
      state: present

- name: jenkins package repository
  yum_repository:
      file: "jenkins"
      name: "{{ RedHat_package.rpm.name }}"
      baseurl: "{{ RedHat_package.rpm.url }}"
      gpgkey: "{{ RedHat_package.key }}"
      description: "{{ RedHat_package.rpm.description }}"


- name: "{{ jenkins_package_state }} Java and Jenkins"
  package:
      name: "{{ item.value }}"
      state: "{{ jenkins_package_state }}"
  loop: "{{ lookup('dict', RedHat_software) }}"
  register: installation_status
